var searchData=
[
  ['receipt',['RECEIPT',['../structBIOS_1_1BEL_1_1RECEIPT.html',1,'BIOS::BEL::RECEIPT'],['../structBIOS_1_1RUS_1_1RECEIPT.html',1,'BIOS::RUS::RECEIPT'],['../classReceipt.html',1,'Receipt']]],
  ['receipt_5ffis_5fdata',['RECEIPT_FIS_DATA',['../structBIOS_1_1BEL_1_1RECEIPT__FIS__DATA.html',1,'BIOS::BEL::RECEIPT_FIS_DATA'],['../structBIOS_1_1RUS_1_1RECEIPT__FIS__DATA.html',1,'BIOS::RUS::RECEIPT_FIS_DATA']]],
  ['receipt_5fnew',['Receipt_new',['../classReceipt__new.html',1,'']]],
  ['receiptsdb',['ReceiptsDb',['../classReceiptsDb.html',1,'']]],
  ['reg_5fmask',['REG_MASK',['../structREG__MASK.html',1,'']]],
  ['registrationstruct',['registrationStruct',['../structregistrationStruct.html',1,'']]],
  ['req_5fname',['REQ_NAME',['../classRequisites_1_1REQ__NAME.html',1,'Requisites']]],
  ['request',['REQUEST',['../structJSON_1_1JSON__SHIFT__DOCUMENT__REPORT_1_1REQUEST.html',1,'JSON::JSON_SHIFT_DOCUMENT_REPORT::REQUEST'],['../structJSON_1_1JSON__MONEY__DOCUMENT__REPORT_1_1REQUEST.html',1,'JSON::JSON_MONEY_DOCUMENT_REPORT::REQUEST'],['../structJSON_1_1JSON__SEARCH__PRODUCT_1_1REQUEST.html',1,'JSON::JSON_SEARCH_PRODUCT::REQUEST'],['../structJSON_1_1JSON__PURCHASE__DOCUMENT__REPORT_1_1REQUEST.html',1,'JSON::JSON_PURCHASE_DOCUMENT_REPORT::REQUEST'],['../structJSON_1_1JSON__COUNTERS__REPORT_1_1REQUEST.html',1,'JSON::JSON_COUNTERS_REPORT::REQUEST'],['../structJSON_1_1JSON__POLL___1_1REQUEST.html',1,'JSON::JSON_POLL_::REQUEST'],['../structJSON_1_1JSON__CASH__INFO__REPORT_1_1REQUEST.html',1,'JSON::JSON_CASH_INFO_REPORT::REQUEST'],['../structJSON_1_1JSON__REGISTER_1_1REQUEST.html',1,'JSON::JSON_REGISTER::REQUEST'],['../structJSON_1_1JSON__UNREGISTER_1_1REQUEST.html',1,'JSON::JSON_UNREGISTER::REQUEST'],['../structJSON_1_1JSON__HANDSHAKE_1_1REQUEST.html',1,'JSON::JSON_HANDSHAKE::REQUEST'],['../structJSON_1_1JSON__KKT__REGISTER__INFO_1_1REQUEST.html',1,'JSON::JSON_KKT_REGISTER_INFO::REQUEST']]],
  ['requisite',['Requisite',['../classRequisites_1_1Requisite.html',1,'Requisites']]],
  ['requisites',['Requisites',['../classRequisites.html',1,'Requisites'],['../structReceipt_1_1requisites.html',1,'Receipt::requisites']]],
  ['response',['RESPONSE',['../structJSON_1_1JSON__CASH__INFO__REPORT_1_1RESPONSE.html',1,'JSON::JSON_CASH_INFO_REPORT::RESPONSE'],['../structJSON_1_1JSON__SEARCH__PRODUCT_1_1RESPONSE.html',1,'JSON::JSON_SEARCH_PRODUCT::RESPONSE'],['../structJSON_1_1JSON__SHIFT__DOCUMENT__REPORT_1_1RESPONSE.html',1,'JSON::JSON_SHIFT_DOCUMENT_REPORT::RESPONSE'],['../structJSON_1_1JSON__MONEY__DOCUMENT__REPORT_1_1RESPONSE.html',1,'JSON::JSON_MONEY_DOCUMENT_REPORT::RESPONSE'],['../structJSON_1_1JSON__PURCHASE__DOCUMENT__REPORT_1_1RESPONSE.html',1,'JSON::JSON_PURCHASE_DOCUMENT_REPORT::RESPONSE'],['../structJSON_1_1JSON__UNREGISTER_1_1RESPONSE.html',1,'JSON::JSON_UNREGISTER::RESPONSE'],['../structJSON_1_1JSON__HANDSHAKE_1_1RESPONSE.html',1,'JSON::JSON_HANDSHAKE::RESPONSE'],['../structJSON_1_1JSON__KKT__REGISTER__INFO_1_1RESPONSE.html',1,'JSON::JSON_KKT_REGISTER_INFO::RESPONSE'],['../structJSON_1_1JSON__REGISTER_1_1RESPONSE.html',1,'JSON::JSON_REGISTER::RESPONSE'],['../structJSON_1_1JSON__POLL___1_1RESPONSE.html',1,'JSON::JSON_POLL_::RESPONSE'],['../structJSON_1_1JSON__COUNTERS__REPORT_1_1RESPONSE.html',1,'JSON::JSON_COUNTERS_REPORT::RESPONSE']]],
  ['rus',['RUS',['../classBIOS_1_1RUS.html',1,'BIOS']]]
];
